name: Deploy static content to Pages

on:
  push:
    branches: ["main"]

  # Permite ejecutar este flujo manualmente desde la pestaña Actions de GitHub
  workflow_dispatch:

# Establece los permisos del GITHUB_TOKEN para permitir el despliegue en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite solo un despliegue concurrente a la vez para evitar colisiones
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inyectar Hash de Commit en el Cache del Service Worker
        run: |
          sed -i 's/const CACHE_NAME = ".*";/const CACHE_NAME = "metar-entrenador-cache-${{ github.sha }}";/g' sw.js

      - name: Configurar Pages
        uses: actions/configure-pages@v4

      - name: Subir artefacto para Pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Sube todo el directorio raíz del proyecto
          path: '.'

      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
